name = "icaur-website"
compatibility_date = "2025-09-13"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_CMS_URL = "https://icaur-cms.cloudhosta.com"
